---
title: "Object Composition: Modeling a Deck of Cards"
type: "video"
description: ""
tags: "object-composition, class, playing-card, oop"
ignore:
- "object-composition-modeling-a-deck-of-cards.md"
